type AuthLogAction =
    | 'loginSuccess'
    | 'loginFailure'
    | 'logoutSuccess'
    | 'resetPasswordSuccess'
    | 'resetPasswordFailure'
    | 'registerSuccess'
    | 'registerFailure'
    | 'deleteUserSuccess'
    | 'deleteUserFailure'
    | 'editUserSuccess'
    | 'editUserFailure'
    | 'addUserSuccess'
    | 'addUserFailure'
